import type { Metadata } from "next";
import { Rye, Libre_Bodoni, Nunito_Sans } from 'next/font/google';
import "./globals.css";

const rye = Rye({
  weight: '400',
  subsets: ['latin'],
});

const libreBodoni = Libre_Bodoni({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Figma Design - Talha",
  description: "Generated by create next app, yes!!!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rye.className} ${libreBodoni.className}`}
      >
        {children}
      </body>
    </html>
  );
}
